/* SPDX-License-Identifier: GPL-2.0+ */
#ifndef __MACH_ECONET_BOOT_H__
#define __MACH_ECONET_BOOT_H__

#define ECONET_FLASH_BASE		0xbfc00000
#define ECONET_SFC_BASE		0xbfa10000
#define ECONET_CHIP_SCU_BASE		0xbfa20000
#define ECONET_FE_SRAM_BASE		0xbfa30000
#define ECONET_FE_SRAM_CACHED		0x9fa30000
#define ECONET_SYSCTL_BASE		0xbfb00000
#define ECONET_SMC_BASE		0xbfb10000
#define ECONET_INTC_BASE		0xbfb40000
#define ECONET_UART0_BASE		0xbfbf0000
#define ECONET_TIMER_BASE		0xbfbf0100

#define ECONET_RESET_CONTROL		(ECONET_SYSCTL_BASE + 0x040)
#define ECONET_FE_SRAM_SEL		(ECONET_SYSCTL_BASE + 0x958)
#define ECONET_SCREG_WR0		(ECONET_SYSCTL_BASE + 0x280)
#define ECONET_REG_SAVE_INFO		(ECONET_SYSCTL_BASE + 0x284)

#define ECONET_TPL_STACK_ADDR		(ECONET_FE_SRAM_BASE + 0xbff0)
#define ECONET_TPL_SAVED_SP		(ECONET_FE_SRAM_BASE + 0xbffc)
#define ECONET_SPL_HEADER_ADDR		(ECONET_FE_SRAM_BASE + 0x40)

#if defined(CONFIG_TARGET_EN751221)
#include <mach/en751221.h>
#define ECONET_DDR_BLOB_ADDR		EN7512_DDR_BLOB_ADDR
#define ECONET_DDR_BLOB_OFFSET		EN7512_DDR_BLOB_OFFSET
#define ECONET_DDR_BLOB_SIZE		EN7512_DDR_BLOB_SIZE
#define ECONET_SPL_IMAGE_OFFSET		EN7512_SPL_IMAGE_OFFSET
#define ECONET_UBOOT_IMAGE_OFFSET	EN7512_UBOOT_IMAGE_OFFSET
#elif defined(CONFIG_TARGET_EN7580)
#include <mach/en7580.h>
#define ECONET_DDR_BLOB_ADDR		EN7580_DDR_BLOB_ADDR
#define ECONET_DDR_BLOB_OFFSET		EN7580_DDR_BLOB_OFFSET
#define ECONET_DDR_BLOB_SIZE		EN7580_DDR_BLOB_SIZE
#define ECONET_SPL_IMAGE_OFFSET		EN7580_SPL_IMAGE_OFFSET
#define ECONET_UBOOT_IMAGE_OFFSET	EN7580_UBOOT_IMAGE_OFFSET
#else
#error "No TPL-capable EcoNet SoC selected"
#endif

#ifndef __ASSEMBLY__
#include <stddef.h>
#include <linux/types.h>

int econet_sfc_read(u32 offset, void *dst, size_t len);
int econet_sfc_init(void);
void econet_run_ddr_blob(void);
#endif

#endif
