/* SPDX-License-Identifier: GPL-2.0+ */
#ifndef __MACH_ECONET_BOOT_H__
#define __MACH_ECONET_BOOT_H__

#define ECONET_FLASH_BASE		0xbfc00000
#define ECONET_SFC_BASE		0xbfa10000
#define ECONET_CHIP_SCU_BASE		0xbfa20000
#define ECONET_FE_SRAM_BASE		0xbfa30000
#define ECONET_FE_SRAM_CACHED		0x9fa30000
#define ECONET_SYSCTL_BASE		0xbfb00000
#define ECONET_SMC_BASE		0xbfb10000
#define ECONET_INTC_BASE		0xbfb40000
#define ECONET_UART0_BASE		0xbfbf0000
#define ECONET_TIMER_BASE		0xbfbf0100

/* Vendor TCBoot geometries used by the MIPS internal-ROM boot path. */
#define ECONET_TCBOOT_128K_SIZE	0x00020000
#define ECONET_TCBOOT_256K_SIZE	0x00040000
#define ECONET_BOOT_IMAGE_SIZE		0x00100000
#define ECONET_TCBOOT_CRC1_OFFSET	0x0001fffc
#define ECONET_TCBOOT_CRC2_OFFSET	0x0003fdfc
#define ECONET_TCBOOT_MINFO_128_OFFSET	0x0000ff00
#define ECONET_TCBOOT_MINFO_128_SIZE	0x00000100
#define ECONET_TCBOOT_MINFO_256_OFFSET	0x0003fe00
#define ECONET_TCBOOT_MINFO_256_SIZE	0x00000200
#define ECONET_TCBOOT_MAGIC_BE_256	0x0000ffb0
#define ECONET_TCBOOT_MAGIC_LE		0x0001fff8
#define ECONET_TCBOOT_MAGIC_MINFO_256	0x0003feb0
#define ECONET_TCBOOT_ECC_INFO		0x00040010

#define ECONET_RESET_CONTROL		(ECONET_SYSCTL_BASE + 0x040)
#define ECONET_FE_SRAM_SEL		(ECONET_SYSCTL_BASE + 0x958)
#define ECONET_SCREG_WR0		(ECONET_SYSCTL_BASE + 0x280)
#define ECONET_REG_SAVE_INFO		(ECONET_SYSCTL_BASE + 0x284)

#define ECONET_SPL_HEADER_ADDR		(ECONET_FE_SRAM_BASE + 0x40)

#if defined(CONFIG_TARGET_EN751221)
#include <mach/en751221.h>
#define ECONET_DDR_BLOB_ADDR		EN7512_DDR_BLOB_ADDR
#define ECONET_DDR_BLOB_ENTRY		EN7512_DDR_BLOB_ENTRY
#define ECONET_DDR_BLOB_OFFSET		EN7512_DDR_BLOB_OFFSET
#define ECONET_DDR_BLOB_SIZE		EN7512_DDR_BLOB_SIZE
#define ECONET_SPL_IMAGE_OFFSET		EN7512_SPL_IMAGE_OFFSET
#define ECONET_UBOOT_IMAGE_OFFSET	EN7512_UBOOT_IMAGE_OFFSET
#define ECONET_TPL_STACK_ADDR		EN7512_TPL_STACK_ADDR
#define ECONET_TPL_SAVED_SP		EN7512_TPL_SAVED_SP
/* Match the older EN751221 image observed on the Nokia G-240G-E. */
#define ECONET_TCBOOT_SIZE		ECONET_TCBOOT_128K_SIZE
#define ECONET_TCBOOT_HEADER_LEN	0x00000000
#define ECONET_SPL_IMAGE_LIMIT		ECONET_TCBOOT_CRC1_OFFSET
#define ECONET_TCBOOT_CHIP_FLASH_INFO	0x00000000
#define ECONET_TCBOOT_WORD28		0x00000000
#define ECONET_TCBOOT_WORD2C		0x00000000
#elif defined(CONFIG_TARGET_EN751627)
#include <mach/en751627.h>
#define ECONET_DDR_BLOB_ADDR		EN751627_DDR_BLOB_ADDR
#define ECONET_DDR_BLOB_ENTRY		EN751627_DDR_BLOB_ENTRY
#define ECONET_DDR_BLOB_OFFSET		EN751627_DDR_BLOB_OFFSET
#define ECONET_DDR_BLOB_SIZE		EN751627_DDR_BLOB_SIZE
#define ECONET_SPL_IMAGE_OFFSET		EN751627_SPL_IMAGE_OFFSET
#define ECONET_UBOOT_IMAGE_OFFSET	EN751627_UBOOT_IMAGE_OFFSET
#define ECONET_TPL_STACK_ADDR		EN751627_TPL_STACK_ADDR
#define ECONET_TPL_SAVED_SP		EN751627_TPL_SAVED_SP
#define ECONET_TCBOOT_SIZE		ECONET_TCBOOT_256K_SIZE
#define ECONET_TCBOOT_HEADER_LEN	ECONET_TCBOOT_256K_SIZE
#define ECONET_SPL_IMAGE_LIMIT		ECONET_TCBOOT_CRC1_OFFSET
#define ECONET_TCBOOT_CHIP_FLASH_INFO	0x00030009
#define ECONET_TCBOOT_WORD28		ECONET_TCBOOT_ECC_INFO
#define ECONET_TCBOOT_WORD2C		0x00000000
#elif defined(CONFIG_TARGET_EN7528)
#include <mach/en7528.h>
#define ECONET_DDR_BLOB_ADDR		EN7528_DDR_BLOB_ADDR
#define ECONET_DDR_BLOB_ENTRY		EN7528_DDR_BLOB_ENTRY
#define ECONET_DDR_BLOB_OFFSET		EN7528_DDR_BLOB_OFFSET
#define ECONET_DDR_BLOB_SIZE		EN7528_DDR_BLOB_SIZE
#define ECONET_SPL_IMAGE_OFFSET		EN7528_SPL_IMAGE_OFFSET
#define ECONET_UBOOT_IMAGE_OFFSET	EN7528_UBOOT_IMAGE_OFFSET
#define ECONET_TPL_STACK_ADDR		EN7528_TPL_STACK_ADDR
#define ECONET_TPL_SAVED_SP		EN7528_TPL_SAVED_SP
#define ECONET_TCBOOT_SIZE		ECONET_TCBOOT_256K_SIZE
#define ECONET_TCBOOT_HEADER_LEN	ECONET_TCBOOT_256K_SIZE
/* LE internal-ROM boot reserves 0x1fff8..0x1fffb for EGAP. */
#define ECONET_SPL_IMAGE_LIMIT		ECONET_TCBOOT_MAGIC_LE
#define ECONET_TCBOOT_CHIP_FLASH_INFO	0x0003000b
#define ECONET_TCBOOT_WORD28		0x00000000
#define ECONET_TCBOOT_WORD2C		ECONET_TCBOOT_ECC_INFO
#elif defined(CONFIG_TARGET_EN7580)
#include <mach/en7580.h>
#define ECONET_DDR_BLOB_ADDR		EN7580_DDR_BLOB_ADDR
#define ECONET_DDR_BLOB_ENTRY		EN7580_DDR_BLOB_ENTRY
#define ECONET_DDR_BLOB_OFFSET		EN7580_DDR_BLOB_OFFSET
#define ECONET_DDR_BLOB_SIZE		EN7580_DDR_BLOB_SIZE
#define ECONET_SPL_IMAGE_OFFSET		EN7580_SPL_IMAGE_OFFSET
#define ECONET_UBOOT_IMAGE_OFFSET	EN7580_UBOOT_IMAGE_OFFSET
#define ECONET_TPL_STACK_ADDR		EN7580_TPL_STACK_ADDR
#define ECONET_TPL_SAVED_SP		EN7580_TPL_SAVED_SP
#define ECONET_TCBOOT_SIZE		ECONET_TCBOOT_256K_SIZE
#define ECONET_TCBOOT_HEADER_LEN	ECONET_TCBOOT_256K_SIZE
#define ECONET_SPL_IMAGE_LIMIT		ECONET_TCBOOT_MAGIC_LE
#define ECONET_TCBOOT_CHIP_FLASH_INFO	0x0003000a
#define ECONET_TCBOOT_WORD28		ECONET_TCBOOT_ECC_INFO
#define ECONET_TCBOOT_WORD2C		0x00000000
#else
#error "No TPL-capable EcoNet SoC selected"
#endif

/* The DDR calibration payload belongs to the first 0xff00-byte boot region. */
#if ECONET_DDR_BLOB_OFFSET + ECONET_DDR_BLOB_SIZE > 0x0000ff00
#error "EcoNet DDR payload exceeds the vendor SPRAM flash window"
#endif

#if ECONET_DDR_BLOB_ENTRY < ECONET_DDR_BLOB_ADDR || \
    ECONET_DDR_BLOB_ENTRY >= ECONET_DDR_BLOB_ADDR + ECONET_DDR_BLOB_SIZE
#error "EcoNet DDR payload entry lies outside the loaded payload"
#endif

#if ECONET_SPL_IMAGE_OFFSET != 0x00010000
#error "EcoNet SPL must start at the vendor second-stage offset 0x10000"
#endif

#if ECONET_SPL_IMAGE_LIMIT > ECONET_TCBOOT_CRC1_OFFSET
#error "EcoNet SPL limit cannot cross the first TCBoot CRC"
#endif

#if ECONET_UBOOT_IMAGE_OFFSET < ECONET_TCBOOT_SIZE
#error "EcoNet U-Boot proper must not overlap the TCBoot region"
#endif

#if ECONET_UBOOT_IMAGE_OFFSET >= ECONET_BOOT_IMAGE_SIZE
#error "EcoNet U-Boot image starts outside the replacement bootloader region"
#endif

#ifndef __ASSEMBLY__
#include <stddef.h>
#include <linux/types.h>

int econet_sfc_read(u32 offset, void *dst, size_t len);
int econet_sfc_init(void);
void econet_run_ddr_blob(void);
#endif

#endif
