# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_PINCTRL_AIROHA)		+= pinctrl-airoha.o

obj-$(CONFIG_PINCTRL_AIROHA_EN751221)	+= pinctrl-en751221.o
obj-$(CONFIG_PINCTRL_AIROHA_EN7528)	+= pinctrl-en7528.o
obj-$(CONFIG_PINCTRL_AIROHA_EN7523)	+= pinctrl-en7523.o
obj-$(CONFIG_PINCTRL_AIROHA_AN7581)	+= pinctrl-an7581.o
obj-$(CONFIG_PINCTRL_AIROHA_AN7583)	+= pinctrl-an7583.o
